### PR TITLE
#64 - implement NO_COLOR

### PR DESCRIPTION
**Pull request by nfultz**
Quick and dirty implementation of NO_COLOR for #64

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks, looks good! Can you please add a test case, and also a bullet point to the NEWS?

**Comment by nfultz** [comment]
I don't understand why my test fails in `R CMD check` but not when I run the line manually in a terminal :(

It seems pretty obvious?

```r
test_that("has_color, NO_COLOR=1", {
  withr::with_envvar(
    c(NO_COLOR="1"),
    expect_false(has_color())
  )
})
```

**Comment by nfultz** [comment]
So I think one of the previous tests is setting the crayon.enabled option and not unsetting it on exit - I've worked around that for now but might be worth hunting down.

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
