### PR TITLE
Adds "xBright" versions of each foreground/background color.

### PR DESCRIPTION
**Pull request by tiegz**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! These seem to be supported in RStudio and the macOS terminal as well, otoh not in iTerm, AFAICT.

Our plan is to focus on the cli package in the future, which (in the dev version) also has its own functions for this, with slightly better defaults, and simpler implementation. So maybe we should de this in cli.

**Comment by tiegz** [comment]
Sounds good @gaborcsardi . I've been looking at ANSI color packages from other languages and they usually have the "bright" colors too (e.g. Chalk), but I'll close this if you don't need it. 

FWIW, it seems handy to have a dedicated library in R that just has the ANSI colors. For example, there are about [83k NPM packages that rely on Chalk](https://libraries.io/npm/chalk), and about [700 Rubygems packages that rely on rainvbow](https://libraries.io/rubygems/rainbow).

One question: I'm new to R, and wondering if there's any sort of a dependency manifest file format for R? Or are libraries always imported directly in your scripts?

**Comment by tiegz** [comment]
> One question: I'm new to R, and wondering if there's any sort of a dependency manifest file format for R? Or are libraries always imported directly in your scripts?

Nevermind, just discovered the DESCRIPTION file.

**Comment by gaborcsardi** [comment]
> FWIW, it seems handy to have a dedicated library in R that just has the ANSI colors. For example, there are about 83k NPM packages that rely on Chalk, and about 700 Rubygems packages that rely on rainvbow.

I'll be happy to add this to the cli package. R packages are somewhat different than npm (etc.) packages, because package maintenance and releases have a higher cost for R packages. So the optimal package size is a bit bigger.

OTOH it is true that a lot of packages use crayon already, so maybe we should add it here as well.

**Pull request closed without merging**
