### PR TITLE
Allow multiple ANSI tags per style code

### PR DESCRIPTION
**Pull request by brodieG**
Changed `codes` to contain lists so that we can use multiple tags per code, although in practice we only use this for `reset` built-in style.  While this is added complexity, it only affects the package onload, and even then performance cost will be minimal.  This allows:

screen shot 2016-08-23 at 8 24 17 pm

Main drawback is that we that we add a bunch of extra close tags that consume bytes, but that seems like a minor side effect.  As a result this did require updating two existing tests although the displayed output is unchanged for them if you `cat` the results.

Ended up being easier to implement fully than to mock up, so here it is.

### CODE REVIEW

**Comment by brodieG** [comment]
Also, haven't updated NEWS or anything like that since I suspect you will probably have some feedback on this one.  Re: coverage decrease, I can't tell for sure but it seem spurious to me based on the diff.  I guess part of the issue is that I'm modifying code that isn't run after package load and as a result won't be covered unless we explicitly re-run it.

**Comment by gaborcsardi** [comment]
I will have to think about how this affects the string manipulation methods, that I'll write at some point.... They might not be affected at all, but I might have assumed there that an open tag always has a matching close tag.

**Comment by brodieG** [comment]
I've worked around the problem I had related to this, so no rush on my account.

**Comment by gaborcsardi** [comment]
A couple of years later... I think this is fine, can you pls rebase it, to get a fresh set of tests? Thanks!

**Comment by brodieG** [comment]
Oh jeez I'll have to dig back and remember what all this was about.  I should have some time next week.

**Comment by brodieG** [comment]
Checked locally on 3.6.2 and things seem to work fine; we'll see what travis/appveyor say.  I made not code changes, but I did add a NEWS entry (and fixed a couple of typos I saw in that file).  Let me know if you need anything else (assuming integration works).

**Comment by brodieG** [comment]
Travis r-devel failed due to a warning (and setting to treat warnings as errors):

> * checking for code/documentation mismatches ... WARNING
> Variables with usage in documentation object 'crayon' but not in code:
> ‘...’

I don't think this comes from this PR and I'm guessing its a new check in R-devel that came in at some point in the past 10 months since the last CI run.

R3.1.3 also fails due to no-longer-available dependencies, so presumably you'll have to remove that version from the build matrix.

**Comment by gaborcsardi** [comment]
Thanks! Strictly speaking this is a breaking change because the `reset` behavior has changed, but I don't think many people used it.

**Pull request merged**
